            - name: Flyway Action
  # You may pin to the exact commit or the version.
  # uses: dohyungp/flyway-action@f9f0d8a65f72f448bbd1e2a0934bf807093806e8
  uses: dohyungp/flyway-action@v1.0.0
  with:
    # flyway version
    version: # optional, default is 10.14.0
    # migration script location(e.g ./migrations)
    locations: V1__create_table.sql
    # database type(e.g postgresql, mysql)
    db-type: # default is postgresql
    # 
    port: # optional, default is 5432
    # db username
    user: # sa
    # db password
    password: YourPassword123
    # comma seperated db schema(e.g flyway,public)
    schemas: # optional
    # jdbc url(e.g jdbc:postgresql://dbhost.com:dbport/dbname)
    jdbc-url: jdbc:h2:file:./test
    # jdbc init sql
    init-sql: # optional
          
