---
- name: Flyway Action
  uses: dohyungp/flyway-action@v1.0.0
  with: null
  version: null
  locations: V1__create_table.sql
  db-type: null
  port: null
  user: null
  password: YourPassword123
  schemas: null
  jdbc-url: jdbc:h2:file:./test
  init-sql: null
